#try/except



# try:
#     #try to run this block of code
#     print(x)
# except:
#     # if an exception exists, run tis block
#     print ('Something went wrong!')

# "x" = 365  (can define x) or run it without to get (except) 

# manue@Manny MINGW64 //manny/Users/manue/Desktop/Pod2_repo/Pod2_Repo/pod2_repo/Manuel/pod2_repo/Manuel (Manuels_Challenges)
# $ "C:/Program Files/Python39/python.exe" //manny/Users/manue/Desktop/Pod2_repo/Pod2_Repo/pod2_repo/Manuel/pod2_repo/Manuel/Video_Practice/exceptions_practice.py
# 365

# /Users/manue/Desktop/Pod2_repo/Pod2_Repo/pod2_repo/Manuel/pod2_repo/Manuel/Video_Practice/exceptions_practice.py
# Something went wrong!

